from typing import Optional
from sqlmodel import Field, SQLModel


class User(SQLModel, table=True):
    id: Optional[int] = Field(
        default=None, primary_key=True
    )  # generated by database, so init with None
    google_id: str
    name: str
    given_name: str
    family_name: str
    email: str
    picture: str
